### ISSUE TITLE
Difference results on building your source code

### ISSUE THREAD

**Issue by huythach** [teocomi/HelloDynamo#2]
I built your source code, and imported to a Dynamo project, but result nodes are different from yours.
Please see the attached file.
![dynamo_customnode](https://user-images.githubusercontent.com/11055389/29915963-580d37aa-8e78-11e7-89aa-e1b887e4f8a7.png)

**Comment by teocomi** [comment]
Hi, it seems that you imported the nodes manually, you should instead let Dynamo load them as packages.
I've updated the code just now to make it more clear. If you set the Start Action in Visual Studio, upon Debug it will automatically copy the dlls to the Dynamo Packages folder (using the Post Build Events), and it will then display correctly in Dynamo.

![image](https://user-images.githubusercontent.com/2679513/29916936-34229992-8e38-11e7-9a60-7ad32f54325b.png)

![image](https://user-images.githubusercontent.com/2679513/29916946-3e296c0e-8e38-11e7-85b0-8ebc83db7194.png)

**Comment by huythach** [comment]
How did you set Post-build event?
I also set Start Action as yours, then import HelloNodeModel.dll file to a Dynamo project, but the result is different.
![2](https://user-images.githubusercontent.com/11055389/29917959-94602acc-8e7e-11e7-9abf-3c1095ac656d.png)

**Comment by teocomi** [comment]
You don't need to manually import the dll, it's loaded automatically by Dynamo. Please refer to the images above which show how to set up the Post built event, alternatively pull the latest changes to this repo.
