### ISSUE TITLE
Selected Elements from linked file

### ISSUE THREAD

**Issue by MEPDOT** [teocomi/HelloDynamo#4]
- i am working on Script to get Parameter from Linked model.
- i used Python Script to get those Elements # i got output.
- i filtered Structural Framing "Categories" # i got output
- i filtered those elements through Nodes "Element.GetParameterValueByName" and "List FilterByBoolMark" with Parameter "Work Plane" # i got ouput.

#Issues

- For the output i am try to filter again through Node "Element.GetParameterValueByName" with Parameter "Type" # Warning: Element.GetParameterValueByName operation failed. Could not obtain element from the current document!  The id may not be valid.

- For the output i am try to filter again through Node "Element.GetParameterValueByName" with Parameter "Family and Type" # Warning: Element.GetParameterValueByName operation failed. Could not obtain element from the current document!  The id may not be valid.

#But i can see the values in Node "Element.Parameters"  (List).

![Selected Elements from linked file](https://user-images.githubusercontent.com/54907495/69238352-c92b3d00-0bbd-11ea-9985-a41ea121afba.png)
[Selected Elements from linked file.zip](https://github.com/teocomi/HelloDynamo/files/3869127/Selected.Elements.from.linked.file.zip)

#May be, I think we may have other Node in different Packages to get that Value. So please suggest me.
# if Possible answer why i cannot get output  

With Regards
Bharath Kumar 
+91 8143994426
mepdot@gmail.com

**Comment by teocomi** [comment]
Hi I'm afraid this is not the place to ask, you should try on th dynamo forum: https://forum.dynamobim.com/

It seems though the the problem is with the levels you are using on the nodes: https://dynamobim.org/introducing-listlevel-working-with-lists-made-easier/
